import org.apache.tools.ant.filters.FixCrLfFilter
import org.apache.tools.ant.filters.ReplaceTokens

apply plugin: 'com.android.library'
// apply plugin: 'kotlin-android'
apply from: file(rootProject.file('module.gradle'))

android {
    flavorDimensions += "api"

    compileSdkVersion rootProject.ext.targetSdkVersion
    buildToolsVersion '36.0.0'
    ndkVersion '28.2.13676358'
    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        externalNativeBuild {
            cmake {
                arguments "-DMODULE_NAME:STRING=$moduleLibraryName",
                        "-DMODULE_VERSION=$moduleVersionCode",
                        "-DMODULE_VERSION_NAME:STRING=$moduleVersion"
            }
        }
    }
    buildFeatures {
        buildConfig true
        prefab true
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "4.0.3"
        }
    }
    namespace 'com.kimjio.umamusumelocalify'
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint {
        targetSdk 36
    }
    testOptions {
        targetSdk 36
    }
}


repositories {
    mavenLocal()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation 'androidx.annotation:annotation:1.9.1'
}

afterEvaluate {
    android.libraryVariants.forEach { variant ->
        def variantCapped = variant.name.capitalize()
        def variantLowered = variant.name.toLowerCase()
        def buildTypeCapped = variant.buildType.name.capitalize()
        def buildTypeLowered = variant.buildType.name.toLowerCase()

        def zipName = "${magiskModuleId.replace('_', '-')}-${moduleVersion}-${buildTypeLowered}.zip"
        def moduleDir = file("$outDir/module_${buildTypeLowered}")

        tasks.register("prepareModuleFiles${variantCapped}", Sync) {
            dependsOn("assemble$variantCapped")

            def templatePath = "$rootDir/template/module"

            into moduleDir

            from(templatePath) {
                exclude "module.prop", 'system.prop', "customize.sh", "service.sh"
            }
            from(templatePath) {
                include 'module.prop'
                expand([
                        id         : magiskModuleId,
                        name       : moduleName,
                        version    : moduleVersion,
                        versionCode: moduleVersionCode.toString(),
                        author     : moduleAuthor,
                        description: "$moduleDescription",
                        updateJson : "${moduleUpdateJson}.json",
                ])
                filter(FixCrLfFilter.class,
                        eol: FixCrLfFilter.CrLf.newInstance("lf"))
            }
            from(templatePath) {
                include 'system.prop'
                expand([
                        version: moduleVersion,
                ])
                filter(FixCrLfFilter.class,
                        eol: FixCrLfFilter.CrLf.newInstance("lf"))
            }
            from(templatePath) {
                include("customize.sh")
                filter(ReplaceTokens.class, tokens: [
                        "MODULE_LIB_NAME": moduleLibraryName
                ])
                filter(FixCrLfFilter.class,
                        eol: FixCrLfFilter.CrLf.newInstance("lf"))
            }
            from(templatePath) {
                include("service.sh")
                filter(ReplaceTokens.class, tokens: [
                        "MODULE_ID"      : magiskModuleId,
                        "MODULE_LIB_NAME": moduleLibraryName
                ])
                filter(FixCrLfFilter.class,
                        eol: FixCrLfFilter.CrLf.newInstance("lf"))
            }

            from("${layout.buildDirectory.asFile.get()}/intermediates/stripped_native_libs/$variantLowered/strip${variantLowered}DebugSymbols/out/lib") {
                into 'lib'
            }

            from("${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/") {
                exclude "compile${buildTypeCapped}JavaWithJavac", "classes"
                doFirst {
                    def sdkDir = project.android.sdkDirectory;
                    def buildToolVersion = project.android.buildToolsVersion;
                    exec {
                        workingDir "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered"
                        commandLine "$sdkDir/build-tools/$buildToolVersion/d8${System.properties['os.name'].toLowerCase().contains('windows'.toLowerCase()) ? ".bat" : ''}",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/graphics/Insets.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/graphics/Insets\$Api29Impl.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/util/ObjectsCompat.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/util/ObjectsCompat\$Api19Impl.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/util/Preconditions.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/DisplayCutoutCompat.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/DisplayCutoutCompat\$Api28Impl.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/DisplayCutoutCompat\$Api30Impl.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/DisplayCutoutCompat\$Api29Impl.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/ViewCompat.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/WindowInsetsCompat.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/WindowInsetsCompat\$Type.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/WindowInsetsCompat\$Impl.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/WindowInsetsCompat\$Impl20.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/WindowInsetsCompat\$Impl21.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/WindowInsetsCompat\$Impl28.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/WindowInsetsCompat\$Impl29.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/WindowInsetsCompat\$Impl30.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/WindowInsetsCompat\$Builder.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/WindowInsetsCompat\$BuilderImpl.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/WindowInsetsCompat\$BuilderImpl20.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/WindowInsetsCompat\$BuilderImpl29.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/WindowInsetsCompat\$BuilderImpl30.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/core/view/WindowInsetsCompat\$TypeImpl30.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/window/layout/util/ContextUtils.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/window/layout/ContextCompatHelperApi24.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/window/layout/ContextCompatHelperApi30.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/window/layout/util/DisplayCompatHelperApi17.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/window/layout/util/DisplayCompatHelperApi28.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/window/layout/WindowMetricsCalculator.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/window/layout/WindowMetricsCalculatorCompat.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/window/layout/WindowMetrics.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/androidx/window/core/Bounds.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/com/kimjio/umamusumelocalify/Hooker.class",
                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantLowered}JavaWithJavac/classes/com/kimjio/umamusumelocalify/MethodCallback.class",
//                                "--classpath",
//                                "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/classes/",
                                "--no-desugaring",
                                "--min-api",
                                minSdkVersion
                    }
                }
                into ''
            }
        }

        tasks.register("zip${variantCapped}", Zip) {
            dependsOn("prepareModuleFiles${variantCapped}")
            from moduleDir
            archiveFileName = zipName
            destinationDirectory = outDir
        }

        tasks.register("push${variantCapped}", Exec) {
            dependsOn("zip${variantCapped}")
            workingDir outDir
            commandLine android.adbExecutable, "push", zipName, "/data/local/tmp/"
        }

        tasks.register("flash${variantCapped}", Exec) {
            dependsOn("push${variantCapped}")
            commandLine android.adbExecutable, "shell", "su", "-c",
                    "magisk --install-module /data/local/tmp/${zipName}"
        }

        tasks.register("flashKSU${variantCapped}", Exec) {
            dependsOn("push${variantCapped}")
            commandLine android.adbExecutable, "shell", "su", "-c",
                    "ksud module install /data/local/tmp/${zipName}"
        }

        tasks.register("flashAP${variantCapped}", Exec) {
            dependsOn("push${variantCapped}")
            commandLine android.adbExecutable, "shell", "su", "-c",
                    "apd module install /data/local/tmp/${zipName}"
        }

        tasks.register("flashAndReboot${variantCapped}", Exec) {
            dependsOn("flash${variantCapped}")
            commandLine android.adbExecutable, "shell", "reboot", "now"
        }

        tasks.register("flashKSUAndReboot${variantCapped}", Exec) {
            dependsOn("flashKSU${variantCapped}")
            commandLine android.adbExecutable, "shell", "reboot", "now"
        }

        tasks.register("flashAPAndReboot${variantCapped}", Exec) {
            dependsOn("flashAP${variantCapped}")
            commandLine android.adbExecutable, "shell", "reboot", "now"
        }

        variant.assembleProvider.get().finalizedBy("zip${variantCapped}")
    }
}
