import org.apache.tools.ant.filters.FixCrLfFilter
import org.apache.tools.ant.filters.ReplaceTokens

import javax.inject.Inject

apply plugin: 'com.android.library'
// apply plugin: 'kotlin-android'
apply from: file(rootProject.file('module.gradle'))

interface InjectedExecOps {
    @Inject
    ExecOperations getExecOps()
}

android {
    flavorDimensions += "api"

    compileSdkVersion = rootProject.ext.targetSdkVersion
    buildToolsVersion = '37.0.0'
    ndkVersion = '29.0.14206865'
    defaultConfig {
        minSdk = rootProject.ext.minSdkVersion
        externalNativeBuild {
            cmake {
                arguments "-DMODULE_NAME:STRING=$moduleLibraryName"
            }
        }
    }
    buildFeatures {
        buildConfig = true
        prefab = true
    }
    externalNativeBuild {
        cmake {
            path = "src/main/cpp/CMakeLists.txt"
            version = "4.1.2"
        }
    }
    namespace = 'com.kimjio.umamusumelocalify'
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    lint {
        targetSdk = 37
    }
    testOptions {
        targetSdk = 37
    }
}


repositories {
    mavenLocal()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation 'androidx.annotation:annotation:1.10.0'
}

androidComponents {
    onVariants(selector().all()) { variant ->
        def variantCapped = variant.name.capitalize()
        def variantLowered = variant.name.toLowerCase()
        def buildTypeCapped = variant.buildType.capitalize()
        def buildTypeLowered = variant.buildType.toLowerCase()

        def zipName = "${magiskModuleId.replace('_', '-')}-${moduleVersion}-${buildTypeLowered}.zip"
        def moduleDir = file("$outDir/module_${buildTypeLowered}")

        tasks.register("prepareModuleFiles${variantCapped}", Sync) {
            dependsOn("assemble${variantCapped}")

            def templatePath = "$rootDir/template/module"

            into moduleDir

            from(templatePath) {
                exclude "module.prop", 'system.prop', "customize.sh", "service.sh"
            }
            from(templatePath) {
                include 'module.prop'
                expand([
                        id         : magiskModuleId,
                        name       : moduleName,
                        version    : moduleVersion,
                        versionCode: moduleVersionCode.toString(),
                        author     : moduleAuthor,
                        description: "$moduleDescription",
                        updateJson : "${moduleUpdateJson}.json",
                ])
                filter(FixCrLfFilter.class,
                        eol: FixCrLfFilter.CrLf.newInstance("lf"))
            }
            from(templatePath) {
                include 'system.prop'
                expand([
                        version: moduleVersion,
                ])
                filter(FixCrLfFilter.class,
                        eol: FixCrLfFilter.CrLf.newInstance("lf"))
            }
            from(templatePath) {
                include("customize.sh")
                filter(ReplaceTokens.class, tokens: [
                        "MODULE_LIB_NAME": moduleLibraryName
                ])
                filter(FixCrLfFilter.class,
                        eol: FixCrLfFilter.CrLf.newInstance("lf"))
            }
            from(templatePath) {
                include("service.sh")
                filter(ReplaceTokens.class, tokens: [
                        "MODULE_ID"      : magiskModuleId,
                        "MODULE_LIB_NAME": moduleLibraryName
                ])
                filter(FixCrLfFilter.class,
                        eol: FixCrLfFilter.CrLf.newInstance("lf"))
            }

            from("${layout.buildDirectory.asFile.get()}/intermediates/stripped_native_libs/$variantLowered/strip${variantCapped}DebugSymbols/out/lib") {
                exclude "**/libdobby.so"
                into 'lib'
            }

            from("${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/") {
                exclude "compile${buildTypeCapped}JavaWithJavac", "classes"
                def injected = project.objects.newInstance(InjectedExecOps)
                doFirst {
                    def sdkDir = androidComponents.sdkComponents.sdkDirectory.get();
                    def buildToolVersion = project.android.buildToolsVersion;
                    def classesDir = file("${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered/compile${variantCapped}JavaWithJavac/classes")
                    def classFiles = project.fileTree(dir: classesDir, include: '**/*.class').files.collect { it.absolutePath }
                    injected.execOps.exec {
                        workingDir "${layout.buildDirectory.asFile.get()}/intermediates/javac/$variantLowered"
                        def d8Command = ["$sdkDir/build-tools/$buildToolVersion/d8${System.properties['os.name'].toLowerCase().contains('windows'.toLowerCase()) ? ".bat" : ''}"]
                        d8Command.addAll(classFiles)
                        d8Command.add("--no-desugaring")
                        d8Command.add("--min-api")
                        d8Command.add(minSdkVersion.apiLevel.toString())
                        commandLine d8Command
                    }
                }
                into ''
            }
        }

        tasks.register("zip${variantCapped}", Zip) {
            dependsOn("prepareModuleFiles${variantCapped}")
            from moduleDir
            archiveFileName = zipName
            destinationDirectory = outDir
        }

        tasks.register("push${variantCapped}", Exec) {
            dependsOn("zip${variantCapped}")
            workingDir outDir
            commandLine androidComponents.sdkComponents.adb.get(), "push", zipName, "/data/local/tmp/"
        }

        tasks.register("flash${variantCapped}", Exec) {
            dependsOn("push${variantCapped}")
            commandLine androidComponents.sdkComponents.adb.get(), "shell", "su", "-c",
                    "magisk --install-module /data/local/tmp/${zipName}"
        }

        tasks.register("flashKSU${variantCapped}", Exec) {
            dependsOn("push${variantCapped}")
            commandLine androidComponents.sdkComponents.adb.get(), "shell", "su", "-c",
                    "ksud module install /data/local/tmp/${zipName}"
        }

        tasks.register("flashAP${variantCapped}", Exec) {
            dependsOn("push${variantCapped}")
            commandLine androidComponents.sdkComponents.adb.get(), "shell", "su", "-c",
                    "apd module install /data/local/tmp/${zipName}"
        }

        tasks.register("flashAndReboot${variantCapped}", Exec) {
            dependsOn("flash${variantCapped}")
            commandLine androidComponents.sdkComponents.adb.get(), "shell", "reboot", "now"
        }

        tasks.register("flashKSUAndReboot${variantCapped}", Exec) {
            dependsOn("flashKSU${variantCapped}")
            commandLine androidComponents.sdkComponents.adb.get(), "shell", "reboot", "now"
        }

        tasks.register("flashAPAndReboot${variantCapped}", Exec) {
            dependsOn("flashAP${variantCapped}")
            commandLine androidComponents.sdkComponents.adb.get(), "shell", "reboot", "now"
        }

        tasks.matching { it.name == "assemble${variantCapped}" }.configureEach {
            it.finalizedBy("zip${variantCapped}")
        }
    }
}
